{
 "title": "EC-site-preview Logs",
 "tags": [
  "laravel",
  "logs",
  "monitoring",
  "preview",
  "EC"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "loki" },
   {
    "name": "channel",
    "label": "Channel",
    "query": {}
   },
   { "name": "environment", "label": "Environment", "query": "preview" },
   { "name": "search", "label": "Search" }
  ]
 },
 "panels": [
  {
   "title": "Log Levels Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(level) (rate({job=\"fluent-bit\", channel=~\"$channel\", environment=\"preview\"} | json | __error__=\"\" [$__interval]))",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "Logs by Channel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(channel) (rate({job=\"fluent-bit\", channel=~\"$channel\", environment=\"preview\"} | json | __error__=\"\" [$__interval]))",
     "legendFormat": "{{channel}}"
    }
   ]
  },
  {
   "title": "Total Errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate({job=\"fluent-bit\", channel=~\"$channel\", environment=\"preview\"} |~ \"ERROR\" [$__range]))"
    }
   ]
  },
  {
   "title": "Total Log Lines",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"fluent-bit\", channel=~\"$channel\", environment=\"preview\"} [$__range]))"
    }
   ]
  },
  {
   "title": "Log Level Distribution",
   "type": "table",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by (level) (count_over_time({job=\"fluent-bit\", channel=~\"$channel\", environment=\"production\"} | json | __error__=\"\" [$__range]))"
    }
   ]
  },
  {
   "title": "Channel Distribution",
   "type": "table",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 8 },
   "targets": [
    {
     "expr": "sum by (channel) (count_over_time({job=\"fluent-bit\", channel=~\"$channel\", environment=\"preview\"} | json | __error__=\"\" [$__range]))"
    }
   ]
  },
  {
   "title": "Multi-Environment Application Logs",
   "type": "logs",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "{job=\"fluent-bit\", channel=~\"$channel\", environment=\"preview\"} |~ \"$search\" | json | line_format \"[{{.environment | upper}}] [{{.channel | upper}}] [{{.level | upper}}] {{.message}}\""
    }
   ]
  }
 ]
}